// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Arc1 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc1, 150);
lv_obj_set_height( ui_Arc1, 150);
lv_obj_set_x( ui_Arc1, 5 );
lv_obj_set_y( ui_Arc1, 10 );
lv_arc_set_value(ui_Arc1, 0);
lv_arc_set_range(ui_Arc1, 0, 5000);

lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xEC1643), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xEC1643), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc1, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Arc2 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc2, 150);
lv_obj_set_height( ui_Arc2, 150);
lv_obj_set_x( ui_Arc2, 0 );
lv_obj_set_y( ui_Arc2, 10 );
lv_obj_set_align( ui_Arc2, LV_ALIGN_TOP_MID );
lv_arc_set_value(ui_Arc2, 0);


ui_Arc3 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc3, 150);
lv_obj_set_height( ui_Arc3, 150);
lv_obj_set_x( ui_Arc3, -5 );
lv_obj_set_y( ui_Arc3, 10 );
lv_obj_set_align( ui_Arc3, LV_ALIGN_TOP_RIGHT );
lv_arc_set_value(ui_Arc3, 0);

lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0x03FD1A), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Arc3, lv_color_hex(0x03FD1A), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc3, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Arc4 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc4, 150);
lv_obj_set_height( ui_Arc4, 150);
lv_obj_set_x( ui_Arc4, 5 );
lv_obj_set_y( ui_Arc4, 0 );
lv_obj_set_align( ui_Arc4, LV_ALIGN_BOTTOM_LEFT );
lv_arc_set_value(ui_Arc4, 0);

lv_obj_set_style_arc_color(ui_Arc4, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc4, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Arc4, lv_color_hex(0x4040FF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc4, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Arc5 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc5, 150);
lv_obj_set_height( ui_Arc5, 150);
lv_obj_set_align( ui_Arc5, LV_ALIGN_BOTTOM_MID );
lv_arc_set_value(ui_Arc5, 0);
lv_arc_set_range(ui_Arc5, 0, 100);

lv_obj_set_style_arc_color(ui_Arc5, lv_color_hex(0xE912EB), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc5, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Arc5, lv_color_hex(0xE912EB), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc5, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Arc6 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc6, 150);
lv_obj_set_height( ui_Arc6, 150);
lv_obj_set_x( ui_Arc6, -5 );
lv_obj_set_y( ui_Arc6, 0 );
lv_obj_set_align( ui_Arc6, LV_ALIGN_BOTTOM_RIGHT );
lv_arc_set_value(ui_Arc6, 0);
lv_arc_set_range(ui_Arc6, 500, 2000);

lv_obj_set_style_arc_color(ui_Arc6, lv_color_hex(0x00FFFC), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc6, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Arc6, lv_color_hex(0x00FFFC), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc6, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -161 );
lv_obj_set_y( ui_Label1, -73 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"CO2: PPM");

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 0 );
lv_obj_set_y( ui_Label2, -74 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"TEMP: *C");

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 161 );
lv_obj_set_y( ui_Label3, -76 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Humidity:\n%");

ui_Label4 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -161 );
lv_obj_set_y( ui_Label4, 83 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"AQI: PPM");

ui_Label5 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -2 );
lv_obj_set_y( ui_Label5, 82 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"VOC: PPM");

ui_Label6 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 161 );
lv_obj_set_y( ui_Label6, 80 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Pressure: \nhPa");

}
